# Homecredit data

| Nombre     | Tamaño muestral | Número de variables | Ratio de default | Ratio del atributo sensible |
|------------|-----------------|---------------------|------------------|-----------------------------|
| Homecredit | 307511          | 122                 | 0.08             | 0.04                        |

**Description of the variables** 

(based on "C:\Users\fscielzo\Documents\IBiDat\Fairness AI\data\homecredit_columns_description.csv")

- SK_ID_CURR,ID of loan in our sample,

- TARGET,"Target variable (1 - client with payment difficulties: he/she had late payment more than X days on at least one of the first Y installments (plazos) of the loan in our sample, 0 - all other cases)",

- NAME_CONTRACT_TYPE,Identification if loan is cash or revolving,

- CODE_GENDER,Gender of the client,

- FLAG_OWN_CAR,Flag if the client owns a car,

- FLAG_OWN_REALTY,Flag if client owns a house or flat,

- CNT_CHILDREN,Number of children the client has,

- AMT_INCOME_TOTAL,Income of the client,


- AMT_CREDIT,Credit amount of the loan,

- AMT_ANNUITY,Loan annuity,

- AMT_GOODS_PRICE,For consumer loans it is the price of the goods for which the loan is given,

- NAME_TYPE_SUITE,Who was accompanying client when he was applying for the loan,

- NAME_INCOME_TYPE,"Clients income type (businessman, working, maternity leave,�)",

- NAME_EDUCATION_TYPE,Level of highest education the client achieved,

- NAME_FAMILY_STATUS,Family status of the client,

- NAME_HOUSING_TYPE,"What is the housing situation of the client (renting, living with parents, ...)",

- REGION_POPULATION_RELATIVE,Normalized population of region where client lives (higher number means the client lives in more populated region),normalized 

- DAYS_BIRTH,Client's age in days at the time of application,time only relative to the application

- DAYS_EMPLOYED,How many days before the application the person started current employment,time only relative to the application

- DAYS_REGISTRATION,How many days before the application did client change his registration,time only relative to the application

- DAYS_ID_PUBLISH,How many days before the application did client change the identity document with which he applied for the loan,time only relative to the application

- OWN_CAR_AGE,Age of client's car,

- FLAG_MOBIL,"Did client provide mobile phone (1=YES, 0=NO)",

- FLAG_EMP_PHONE,"Did client provide work phone (1=YES, 0=NO)",

- FLAG_WORK_PHONE,"Did client provide home phone (1=YES, 0=NO)",

- FLAG_CONT_MOBILE,"Was mobile phone reachable (1=YES, 0=NO)",

- FLAG_PHONE,"Did client provide home phone (1=YES, 0=NO)",

- FLAG_EMAIL,"Did client provide email (1=YES, 0=NO)",

- OCCUPATION_TYPE,What kind of occupation does the client have,

- CNT_FAM_MEMBERS,How many family members does client have,

- REGION_RATING_CLIENT,"Our rating of the region where client lives (1,2,3)",

- REGION_RATING_CLIENT_W_CITY,"Our rating of the region where client lives with taking city into account (1,2,3)",

- WEEKDAY_APPR_PROCESS_START,On which day of the week did the client apply for the loan,

- HOUR_APPR_PROCESS_START,Approximately at what hour did the client apply for the loan,rounded

- REG_REGION_NOT_LIVE_REGION,"Flag if client's permanent address does not match contact address (1=different, 0=same, at region level)",

- REG_REGION_NOT_WORK_REGION,"Flag if client's permanent address does not match work address (1=different, 0=same, at region level)",

- LIVE_REGION_NOT_WORK_REGION,"Flag if client's contact address does not match work address (1=different, 0=same, at region level)",

- REG_CITY_NOT_LIVE_CITY,"Flag if client's permanent address does not match contact address (1=different, 0=same, at city level)",

- REG_CITY_NOT_WORK_CITY,"Flag if client's permanent address does not match work address (1=different, 0=same, at city level)",

- LIVE_CITY_NOT_WORK_CITY,"Flag if client's contact address does not match work address (1=different, 0=same, at city level)",

- ORGANIZATION_TYPE,Type of organization where client works,

- EXT_SOURCE_1,Normalized score from external data source,normalized

- EXT_SOURCE_2,Normalized score from external data source,normalized

- EXT_SOURCE_3,Normalized score from external data source,normalized

- APARTMENTS_AVG,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized

- BASEMENTAREA_AVG,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized

- YEARS_BEGINEXPLUATATION_AVG,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized

- YEARS_BUILD_AVG,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized

- COMMONAREA_AVG,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized

- ELEVATORS_AVG,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized

- ENTRANCES_AVG,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized

- FLOORSMAX_AVG,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized

- FLOORSMIN_AVG,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized

- LANDAREA_AVG,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized

- LIVINGAPARTMENTS_AVG,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized

- LIVINGAREA_AVG,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized

- NONLIVINGAPARTMENTS_AVG,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized

- NONLIVINGAREA_AVG,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized

- APARTMENTS_MODE,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized

- BASEMENTAREA_MODE,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized

- YEARS_BEGINEXPLUATATION_MODE,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized

- YEARS_BUILD_MODE,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized

- COMMONAREA_MODE,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized

- ELEVATORS_MODE,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized

- ENTRANCES_MODE,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized

- FLOORSMAX_MODE,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized

- FLOORSMIN_MODE,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized

- LANDAREA_MODE,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized

- LIVINGAPARTMENTS_MODE,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized

- LIVINGAREA_MODE,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized

- NONLIVINGAPARTMENTS_MODE,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized

- NONLIVINGAREA_MODE,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized

- APARTMENTS_MEDI,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized

- BASEMENTAREA_MEDI,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized

- YEARS_BEGINEXPLUATATION_MEDI,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized

- YEARS_BUILD_MEDI,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized

- COMMONAREA_MEDI,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized

- ELEVATORS_MEDI,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized

- ENTRANCES_MEDI,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized

- FLOORSMAX_MEDI,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized

- FLOORSMIN_MEDI,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized

- LANDAREA_MEDI,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized

- LIVINGAPARTMENTS_MEDI,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized

- LIVINGAREA_MEDI,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized

- NONLIVINGAPARTMENTS_MEDI,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized

- NONLIVINGAREA_MEDI,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized

- FONDKAPREMONT_MODE,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized

- HOUSETYPE_MODE,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized

- TOTALAREA_MODE,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized

- WALLSMATERIAL_MODE,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized

- EMERGENCYSTATE_MODE,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized

- OBS_30_CNT_SOCIAL_CIRCLE,How many observation of client's social surroundings with observable 30 DPD (days past due) default,

- DEF_30_CNT_SOCIAL_CIRCLE,How many observation of client's social surroundings defaulted on 30 DPD (days past due),

- OBS_60_CNT_SOCIAL_CIRCLE,How many observation of client's social surroundings with observable 60 DPD (days past due) default,

- DEF_60_CNT_SOCIAL_CIRCLE,How many observation of client's social surroundings defaulted on 60 (days past due) DPD,

- DAYS_LAST_PHONE_CHANGE,How many days before application did client change phone,

- FLAG_DOCUMENT_2,Did client provide document 2,

- FLAG_DOCUMENT_3,Did client provide document 3,

- FLAG_DOCUMENT_4,Did client provide document 4,

- FLAG_DOCUMENT_5,Did client provide document 5,

- FLAG_DOCUMENT_6,Did client provide document 6,

- FLAG_DOCUMENT_7,Did client provide document 7,

- FLAG_DOCUMENT_8,Did client provide document 8,

- FLAG_DOCUMENT_9,Did client provide document 9,

- FLAG_DOCUMENT_10,Did client provide document 10,

- FLAG_DOCUMENT_11,Did client provide document 11,

- FLAG_DOCUMENT_12,Did client provide document 12,

- FLAG_DOCUMENT_13,Did client provide document 13,

- FLAG_DOCUMENT_14,Did client provide document 14,

- FLAG_DOCUMENT_15,Did client provide document 15,

- FLAG_DOCUMENT_16,Did client provide document 16,

- FLAG_DOCUMENT_17,Did client provide document 17,

- FLAG_DOCUMENT_18,Did client provide document 18,

- FLAG_DOCUMENT_19,Did client provide document 19,

- FLAG_DOCUMENT_20,Did client provide document 20,

- FLAG_DOCUMENT_21,Did client provide document 21,

- AMT_REQ_CREDIT_BUREAU_HOUR,Number of enquiries to Credit Bureau about the client one hour before application,

- AMT_REQ_CREDIT_BUREAU_DAY,Number of enquiries to Credit Bureau about the client one day before application (excluding one hour before application),

- AMT_REQ_CREDIT_BUREAU_WEEK,Number of enquiries to Credit Bureau about the client one week before application (excluding one day before application),

- AMT_REQ_CREDIT_BUREAU_MON,Number of enquiries to Credit Bureau about the client one month before application (excluding one week before application),

- AMT_REQ_CREDIT_BUREAU_QRT,Number of enquiries to Credit Bureau about the client 3 month before application (excluding one month before application),

- AMT_REQ_CREDIT_BUREAU_YEAR,Number of enquiries to Credit Bureau about the client one day year (excluding last 3 months before application),

## Requirements

In [13]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from PyMachineLearning.preprocessing import encoder, imputer
from aif360.datasets import StandardDataset

from PyFairnessAI.data import privileged_groups_sens, unprivileged_groups_sens

## Processing the data

In [14]:
homecredit_data = pd.read_csv(r"C:\Users\fscielzo\Documents\IBiDat\Fairness AI\data\homecredit.csv", 
                              header=0, sep=',', quotechar='"')
homecredit_data.head()

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0

### Processing without pipelines

In [15]:
# Non-data-leakage processing

## Identifying categorical and quantitative variables

cat_cols = ['NAME_CONTRACT_TYPE', 'CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'NAME_TYPE_SUITE',
            'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE', 'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE',
            'OCCUPATION_TYPE', 'WEEKDAY_APPR_PROCESS_START', 'ORGANIZATION_TYPE', 'FONDKAPREMONT_MODE',
            'HOUSETYPE_MODE', 'WALLSMATERIAL_MODE', 'EMERGENCYSTATE_MODE']
            # CODE_GENDER is not considered since we will use AGE as sensitive attribute


quant_cols = [x for x in homecredit_data.columns if x not in cat_cols + ['SK_ID_CURR']]
             # SK_ID_CURR is not considered as quant col

## NA values in OWN_CAR_AGE converted to 0: "no car"
homecredit_data.loc[homecredit_data['FLAG_OWN_CAR'] == "N", "OWN_CAR_AGE"] = 0

## Conversion of age from days_from_birth to age (in years)
homecredit_data['AGE'] = - homecredit_data['DAYS_BIRTH'].astype('float') / 365

## Dropping CODE_GENDER (not considered since we will use AGE as sensitive attribute), SK_ID_CURR and DAYS_BIRTH (we now have AGE)
cols_to_drop = ['DAYS_BIRTH', 'SK_ID_CURR', 'CODE_GENDER']
homecredit_data = homecredit_data.drop(columns=cols_to_drop)

## Transforming AGE into categorical (this doesn't lead to data-leakage  but must be done after imputing)
homecredit_data['AGE'] = homecredit_data['AGE'].map(lambda x : 1 if x >= 25 else 0, # AGE will be the sensitive variable and 1 (>= 25) the label of the privileged class
                                                    na_action='ignore') 

## Updating columns list after above process
quant_cols = [x for x in quant_cols if x not in cols_to_drop] 
cat_cols = [x for x in cat_cols if x not in cols_to_drop] + ['AGE']


# Data-leakage processing

## NA values converted to median in numeric variables:
homecredit_data[quant_cols] = homecredit_data[quant_cols].fillna(homecredit_data[quant_cols].median())

## NA values converted to most frequent in categorical variables
homecredit_data[cat_cols] = homecredit_data[cat_cols].fillna(homecredit_data[cat_cols].mode().iloc[0])

## OneHot encoding the categorical variables (this doesn't lead to data-leakage necessarily but must be done after imputing)
encoder_ = OneHotEncoder(handle_unknown='ignore', sparse_output=False, drop='first')
onehotencoding_arr = encoder_.fit_transform(homecredit_data[cat_cols])
onehotencoding_df = pd.DataFrame(onehotencoding_arr, columns=encoder_.get_feature_names_out())
homecredit_data = pd.concat([homecredit_data[quant_cols], onehotencoding_df], axis=1)

In [16]:
homecredit_data.head()

,TARGET,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,REGION_POPULATION_RELATIVE,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,...,HOUSETYPE_MODE_specific housing,HOUSETYPE_MODE_terraced house,WALLSMATERIAL_MODE_Mixed,WALLSMATERIAL_MODE_Monolithic,WALLSMATERIAL_MODE_Others,WALLSMATERIAL_MODE_Panel,"WALLSMATERIAL_MODE_Stone, brick",WALLSMATERIAL_MODE_Wooden,EMERGENCYSTATE_MODE_Yes,AGE_1
0,1,0,202500.0,406597.5,24700.5,351000.0,0.018801,-637,-3648.0,-2120,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1,0,0,270000.0,1293502.5,35698.5,1129500.0,0.003541,-1188,-1186.0,-291,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,0,0,67500.0,135000.0,6750.0,135000.0,0.010032,-225,-4260.0,-2531,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
3,0,0,135000.0,312682.5,29686.5,297000.0,0.008019,-3039,-9833.0,-2437,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
4,0,0,121500.0,513000.0,21865.5,513000.0,0.028663,-3038,-4311.0,-3458,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0

### Processing with pipelines

In [17]:
homecredit_data = pd.read_csv(r"C:\Users\fscielzo\Documents\IBiDat\Fairness AI\data\homecredit.csv", header=0, sep=',', quotechar='"')
homecredit_data.head()

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0

In [18]:
# Non-data-leakage processing

## Identifying categorical and quantitative variables

cat_cols = ['NAME_CONTRACT_TYPE', 'CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'NAME_TYPE_SUITE',
            'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE', 'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE',
            'OCCUPATION_TYPE', 'WEEKDAY_APPR_PROCESS_START', 'ORGANIZATION_TYPE', 'FONDKAPREMONT_MODE',
            'HOUSETYPE_MODE', 'WALLSMATERIAL_MODE', 'EMERGENCYSTATE_MODE']
            # CODE_GENDER is not considered since we will use AGE as sensitive attribute


quant_cols = [x for x in homecredit_data.columns if x not in cat_cols + ['SK_ID_CURR']]
             # SK_ID_CURR is not considered as quant col

## NA values in OWN_CAR_AGE converted to 0: "no car"
homecredit_data.loc[homecredit_data['FLAG_OWN_CAR'] == "N", "OWN_CAR_AGE"] = 0

## Conversion of age from days_from_birth to age (in years)
homecredit_data['AGE'] = - homecredit_data['DAYS_BIRTH'].astype('float') / 365

## Dropping CODE_GENDER (not considered since we will use AGE as sensitive attribute), SK_ID_CURR and DAYS_BIRTH (we now have AGE)
cols_to_drop = ['DAYS_BIRTH', 'SK_ID_CURR', 'CODE_GENDER']
homecredit_data = homecredit_data.drop(columns=cols_to_drop)

## Transforming AGE into categorical (this doesn't lead to data-leakage  but must be done after imputing)
homecredit_data['AGE'] = homecredit_data['AGE'].map(lambda x : 1 if x >= 25 else 0, # AGE will be the sensitive variable and 1 (>= 25) the label of the privileged class
                                                    na_action='ignore') 

## Updating columns list after above process
quant_cols = [x for x in quant_cols if x not in cols_to_drop] 
cat_cols = [x for x in cat_cols if x not in cols_to_drop] + ['AGE']

In [19]:
quant_pipeline = Pipeline([
    ('imputer', imputer(apply=True, method='simple_median'))
    ])

cat_pipeline = Pipeline([
    ('imputer', imputer(apply=True, method='simple_most_frequent')),
    ('encoder', encoder(method='one-hot', drop='first'))
    ])

quant_cat_processing = ColumnTransformer(transformers=[('quant', quant_pipeline, quant_cols),
                                                       ('cat', cat_pipeline, cat_cols)])

In [20]:
processed_data = quant_cat_processing.fit_transform(X=homecredit_data)
# Updating cat cols
cat_cols = quant_cat_processing.named_transformers_['cat']['encoder'].get_feature_names_out(cat_cols).tolist()
# Transforming 'processed_data' into Pandas df
homecredit_data = pd.DataFrame(processed_data, columns = quant_cols + cat_cols)

In [21]:
homecredit_data.head()

,TARGET,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,REGION_POPULATION_RELATIVE,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,...,HOUSETYPE_MODE_specific housing,HOUSETYPE_MODE_terraced house,WALLSMATERIAL_MODE_Mixed,WALLSMATERIAL_MODE_Monolithic,WALLSMATERIAL_MODE_Others,WALLSMATERIAL_MODE_Panel,"WALLSMATERIAL_MODE_Stone, brick",WALLSMATERIAL_MODE_Wooden,EMERGENCYSTATE_MODE_Yes,AGE_1
0,1.0,0.0,202500.0,406597.5,24700.5,351000.0,0.018801,-637.0,-3648.0,-2120.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1,0.0,0.0,270000.0,1293502.5,35698.5,1129500.0,0.003541,-1188.0,-1186.0,-291.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,0.0,0.0,67500.0,135000.0,6750.0,135000.0,0.010032,-225.0,-4260.0,-2531.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
3,0.0,0.0,135000.0,312682.5,29686.5,297000.0,0.008019,-3039.0,-9833.0,-2437.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
4,0.0,0.0,121500.0,513000.0,21865.5,513000.0,0.028663,-3038.0,-4311.0,-3458.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0

### Transforming to `aif360` dataset

In [31]:
response_name = 'TARGET'
favorable_response_label = [0]
sens_cols = ['AGE_1']
privileged_sens_label = [[1]]

homecredit_data_aif = StandardDataset(df=homecredit_data,
                                      label_name=response_name,
                                      favorable_classes=favorable_response_label,
                                      protected_attribute_names=sens_cols,
                                      privileged_classes=privileged_sens_label)

In [32]:
homecredit_data_aif

               instance weights     features                              \

                                CNT_CHILDREN AMT_INCOME_TOTAL AMT_CREDIT
instance names
0                           1.0          0.0         202500.0   406597.5
1                           1.0          0.0         270000.0  1293502.5
2                           1.0          0.0          67500.0   135000.0
3                           1.0          0.0         135000.0   312682.5
4                           1.0          0.0         121500.0   513000.0
...                         ...          ...              ...        ...
307506                      1.0          0.0         157500.0   254700.0
307507                      1.0          0.0          72000.0   269550.0
307508                      1.0          0.0         153000.0   677664.0
307509                      1.0          0.0         171000.0   370107.0
307510                      1.0          0.0         157500.0   675000.0

                                                                       \

               AMT_ANNUITY AMT_GOODS_PRICE REGION_POPULATION_RELATIVE
instance names
0                  24700.5        351000.0                   0.018801
1                  35698.5       1129500.0                   0.003541
2                   6750.0        135000.0                   0.010032
3                  29686.5        297000.0                   0.008019
4                  21865.5        513000.0                   0.028663
...                    ...             ...                        ...
307506             27558.0        225000.0                   0.032561
307507             12001.5        225000.0                   0.025164
307508             29979.0        585000.0                   0.005002
307509             20205.0        319500.0                   0.005313
307510             49117.5        675000.0                   0.046220

                                                                ...  \
                                                                ...
               DAYS_EMPLOYED DAYS_REGISTRATION DAYS_ID_PUBLISH  ...
instance names                                                  ...
0                     -637.0           -3648.0         -2120.0  ...
1                    -1188.0           -1186.0          -291.0  ...
2                     -225.0           -4260.0         -2531.0  ...
3                    -3039.0           -9833.0         -2437.0  ...
4                    -3038.0           -4311.0         -3458.0  ...
...                      ...               ...             ...  ...
307506                -236.0           -8456.0         -1982.0  ...
307507              365243.0           -4388.0         -4090.0  ...
307508               -7921.0           -6737.0         -5150.0  ...
307509               -4786.0           -2562.0          -931.0  ...
307510               -1262.0           -5128.0          -410.0  ...

                                                                       \

               HOUSETYPE_MODE_terraced house WALLSMATERIAL_MODE_Mixed
instance names
0                                        0.0                      0.0
1                                        0.0                      0.0
2                                        0.0                      0.0
3                                        0.0                      0.0
4                                        0.0                      0.0
...                                      ...                      ...
307506                                   0.0                      0.0
307507                                   0.0                      0.0
307508                                   0.0                      0.0
307509                                   0.0                      0.0
307510                                   0.0                      0.0

                                                                        \

               WALLSMATERIAL_MODE_Monolithic WALLSMATERIAL_MODE_Others
instance names
0                                        0.0                       0.0
1                                        0.0                       0.0
2                                        0.0                       0.0
3                                        0.0                       0.0
4                                        0.0                       0.0
...                                      ...                       ...
307506                                   0.0                       0.0
307507                                   0.0                       0.0
307508                                   0.0                       0.0
307509                                   0.0                       0.0
307510                                   0.0                       0.0

                                                                         \

               WALLSMATERIAL_MODE_Panel WALLSMATERIAL_MODE_Stone, brick
instance names
0                                   0.0                             1.0
1                                   0.0                             0.0
2                                   1.0                             0.0
3                                   1.0                             0.0
4                                   1.0                             0.0
...                                 ...                             ...
307506                              0.0                             1.0
307507                              0.0                             1.0
307508                              1.0                             0.0
307509                              0.0                             1.0
307510                              1.0                             0.0

                                                                  \

               WALLSMATERIAL_MODE_Wooden EMERGENCYSTATE_MODE_Yes
instance names
0                                    0.0                     0.0
1                                    0.0                     0.0
2                                    0.0                     0.0
3                                    0.0                     0.0
4                                    0.0                     0.0
...                                  ...                     ...
307506                               0.0                     0.0
307507                               0.0                     0.0
307508                               0.0                     0.0
307509                               0.0                     0.0
307510                               0.0                     0.0

                                   labels
               protected attribute
                             AGE_1
instance names
0                              1.0    1.0
1                              1.0    0.0
2                              1.0    0.0
3                              1.0    0.0
4                              1.0    0.0
...                            ...    ...
307506                         1.0    0.0
307507                         1.0    0.0
307508                         1.0    0.0
307509                         1.0    1.0
307510                         1.0    0.0

[307511 rows x 228 columns]

In [33]:
homecredit_data_aif.features.shape # data shape

(307511, 226)

In [34]:
homecredit_data_aif.label_names # Response name

['TARGET']

In [35]:
homecredit_data_aif.favorable_label # Y label of the favorable group
# TARGET = 1 <--> good candidate for the credit

0.0

In [36]:
homecredit_data_aif.unfavorable_label # Y label of the unfavorable group
# TARGET = 0 <--> bad candidate for the credit

1.0

In [37]:
homecredit_data_aif.protected_attribute_names # sensitive variables

['AGE_1']

In [38]:
privileged_groups_sens(homecredit_data_aif) # Label of the privileged group for each sensitive predictor
# AGE = 1 <--> age >= 25

{'AGE_1': 1}

In [39]:
unprivileged_groups_sens(homecredit_data_aif) # Label of the unprivileged group for each sensitive predictor
# AGE = 0 <--> age < 25

{'AGE_1': 0}